### ISSUE TITLE
DB design could be improved

### ISSUE THREAD

**Issue by longnd** [quanglochuynh/loc_scrap_frontend#20]
## Issue
The current DB design could be improved
- Lack of foreign key constraint in the `MyKeywords` table on the `createdUserID` column. 
- For the existing foreign key on the `keywordID` column, Index should be created to speed up the join as PosgreSQL will not create the index automatically
> declaration of a foreign key constraint does not automatically create an index on the referencing columns ([source](https://www.postgresql.org/docs/current/ddl-constraints.html))

Beside that, looking at the implementation in the backend app, the application expect that there won't be duplicate keywords (it check for existing keywords before creating) for the same users. If it is the expected behavior, a unique constraint should be applied on the `keywordID` & `createdUserID` columns.

However, that should not be the behavior, given that even for the same keyword, the search result could be different each time, even for the sam user. Example: when searching for "weather focast", Google returns different result each day.

**Comment by quanglochuynh** [comment]
I have added the foreign key constants, as well as the index for keywordID column. I really appreciate your advice 😀
