### ISSUE TITLE
Source code organization needs major improvement

### ISSUE THREAD

**Issue by longnd** [quanglochuynh/loc_scrap_frontend#22]
## Issue
There are some giant functions in the codebase, each handle multiple responsibilites, all of them are sacrifying the readability, maintainability, reusability & testability. Some example:
- https://github.com/quanglochuynh/loc_scrap_backend/blob/e9a8947adfb6b6463f4cb6eb93e3427328ac31fa/src/controllers/myKeyword/uploadFile.ts#L10-L118
- https://github.com/quanglochuynh/loc_scrap_backend/blob/e9a8947adfb6b6463f4cb6eb93e3427328ac31fa/src/utilities/scraper.ts#L5-L159

 The above function does:
 - sending search requests
 - Processes the HTML response
 - Analyzes the class names used in search result containers
 - Builds a list of search results (resultList)
 - Cleans up and prepares the result payload

all in a single function. It is too much to read, test and maitain that function 😅

Each of the mentioned examples should have been separated into different concerns, making each piece of functionality becomes clearer, easier to maintain, easier to test, and more reusable. This also allows other functions to potentially leverage the same sub-functions when needed.

**Comment by quanglochuynh** [comment]
I have refactored the mess. Sorry for the inconsistency in my scraping codes because I tested them in other repo and the deadline of 7 days was a bit tight for me. I really appreciate your feedback 😀
